chore: create button atoms
LABS-EU3/frontend_community_calendar pull request #4
Opened 2019-12-18 21:24 UTC by theallegrarr

### Description ?
A reusable button component has been created, it receives size, background color(optional) and font color(optional) as props, Stories were also set up to view variations of the component, and tests were added to check the component

#### Chore

#### How Has This Been Tested?
- Automated tests and manual checks

#### Checklist
- [x] 3 button types created(small,medium,large)
- [x] Stories created for the buttons and their props
- [x] Tests written for the buttons

2019-12-18 21:25 UTC, theallegrarr commented
![](https://github.trello.services/images/mini-trello-icon.png) [Create Button atomic component](https://trello.com/c/1LmHJWnT/36-create-button-atomic-component)

2019-12-19 13:22 UTC, twumm commented on components/atoms/ButtonAtoms/index.js
> +    background-color: ${props => props.background || '#CE5374'};
Considering props is already defined in the outer Buttons function, re-declaring props here will be repetition. 
One way to go about it is to remove the props from line 4

2019-12-19 13:27 UTC, twumm commented on components/atoms/ButtonAtoms/index.stories.js
> +export const SmallButton = () => <ButtonComponent size="small" text="Small" />;
variables here can be camel case - `smallButton`.

2019-12-19 13:33 UTC, twumm requested changes
eslint had some sections marked up, can you kindly resolve those?

For the Button, we can keep the styles DRY by using props in this example below:
```
const Arrow = styled.i`
  border: solid #757575;
  border-width: 0 4px 4px 0;
  display: inline-block;
  padding: 6px;
  cursor: pointer;

  ${props => props.right && css`
    transform: rotate(-45deg);
    -webkit-transform: rotate(-45deg);
  `}
  ${props => props.left && css`
    transform: rotate(135deg);
    -webkit-transform: rotate(135deg);
    padding: 4px;
  `}
`;
```

In the above, the left and right arrows will inherit all styles for the regular arrow.

Please let me know if this is fine by you.
Perhaps by the time you get back, I will have had some other components you can checkout since the Heading component was quite unusual with me using `React.createElement`.

*Also*, you can delete the old Button folder so your folder can be named Button.

Cheers

2019-12-20 15:11 UTC, twumm approved these changes
Awesome work on the refactor! Please merge in.

2019-12-20 15:12 UTC, merged